Quiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='version1',
      description="Test description",
   ),
   public=True,
   permission_classes=(permissions.AllowAny),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account', include('account.urls')),
    path('', include('app.urls')),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc')
]

api_urls = [
    path('api/version1/user/', include('account.api.version1.urls')),
    path('api/version1/app/', include('app.api.version1.urls')),
]

urlpatterns += api_urls
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path

from account.views import SignUpView, login_view, logout_view, UserProfileView, UserProfileUpdateView

app_name = 'account'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/update/', UserProfileUpdateView.as_view(), name='profile_update'),
]

app/urls.py
from django.urls import path

from .views import HomePageView, question_list, result_list, TestsView

app_name = 'app'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('question/<slug:slug>', question_list, name='question_list'),
    path('result/', result_list, name='result_list'),
    path('tests/', TestsView.as_view(), name='tests')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
    <title>{% block title %} {% endblock %}</title>
</head>
<body>

<header class="center-el">
    <a href="{% url 'app:home'%}"> Home </a>
    {% if user.is_authenticated %}
        <a href="{% url 'account:profile' %}"> My Profile</a>
        <a href="{% url 'app:tests' %}">Tests</a>
        <a href="{% url 'account:logout' %}">Logout</a>
        
    {% else %}    
        <a href="{% url 'account:signup' %}"> SignUp </a>
        <a href="{% url 'account:login' %}"> Login </a>

    {% endif %}

</header>
<div>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}

      <div class="landing-page">
        <div class="content">
          <div class="container">
            <div class="info">
              <h1>Welcome to QuizTests</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus odit nihil ullam nesciunt quidem iste, Repellendus odit nihil</p>
                {% if not user.is_authenticated %}
                    <a href="{% url 'account:login' %}"> Login </a>
                {% endif %}
            </div>
            <div class="image center-el">
                <span class="spin-animation center-el"></span>
                <span class="animation-text">Hello</span>
            </div>
          </div>
        </div>
      </div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
    <form method="post" id="login" class="centered form-card">
        <h2>Login</h2>
        {% csrf_token %}
        {{ form }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block title %}User Profile{% endblock %}

{% block content %}
    <div class="profile centered">
        {% if user.image %}
            <img src="{{ user.image.url }}" class="profile-img">
        {% else %}
            <p>No photo uploaded.</p>
        {% endif %}
        <h1>My Profile</h1>
        <p>Name: {{ user.get_full_name }}</p>
        <p>Phone: {{ user.phone }}</p>
        <p>Email: {{ user.email }}</p>
        <a href="{% url 'app:result_list' %}">Result list</a> |
        <a href="{% url 'account:profile_update' %}">
            <i class="fa-solid fa-pen"></i>
        </a>
    </div>
{% endblock %}

templates/profile_update.html
{% extends 'base.html' %}

{% block title %}Edit Profile {% endblock %}

{% block content %}
    <h1>Edit Profile</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
{% endblock %}

templates/question_list.html
{% extends 'base.html' %}

{% block title %} Question List {% endblock %}

{% block content %}
    <h3>Question List</h3>
    <hr>
    <form method="post">
    {% csrf_token %}
    {% for question in questions %}
        <p>{{ question.name }}</p>
        {% for answer in question.answers.all %}
            <label>{{ answer.name }}</label>
            <input type="radio" name="{{ question.name }}" value="{{ answer.pk}}">
        {% endfor %}
    {% endfor %}
    <br>
    <br>
        <button type="submit"> Send </button>
    </form>
{% endblock %}

templates/result.html
{% extends 'base.html' %}
{#{% load floatformat %}#}

{% block title %} Result {% endblock %}


{% block content %}
    
    <h2> Result </h2>
    <hr>
    <p>Category: {{ result.category }}</p>
    <p>Total questions: {{ result.total_questions }}</p>
    <p>Total answers: {{ result.total_correct }}</p>
    <p>Total score: {{ result.score }}</p>
    
{% endblock %}

templates/result_list.html
{% extends 'base.html' %}

{% block title %} Result list {% endblock %}

{% block content %}
    <h1> Result List Page</h1>

    <hr>
    <form method="get">
    {% csrf_token %}
    {{ filter.form }}
    <button type="submit" >Search</button>

    </form>

    <form method="post">
    {% csrf_token %}
    <table border="2">
        <thead>
        <tr>
            <td> ID </td>
            <td> User </td>
            <td> Total question </td>
            <td> correct </td>
            <td> Score </td>
            <td> Date </td>
            <td> Category </td>
        </tr>
        </thead>
        <tbody>
        {% for result in filter.qs %}
            {% if result.user == user %}
            <tr>
                <td> {{ result.id }}</td>
                <td> {{ result.user.phone }}</td>
                <td> {{ result.total_questions }}</td>
                <td> {{ result.total_correct }}</td>
                <td> {{ result.score }}</td>
                <td> {{ result.created_at | date:'Y-m-d' }}</td>
                <td> {{ result.category.name }}</td>
            </tr>
            {% endif %}
        {% endfor %}
        </tbody>


    </table>
    </form>

{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %} Sign Up {% endblock %}

{% block content %}
    <form method="post" class="centered form-card">
        <h2>Sign Up</h2>
        {% csrf_token  %}
        {{ form }}
        <button type="submit"> SignUp </button>
    </form>
{% endblock %}

templates/tests.html
{% extends 'base.html' %}

{% block title %} Tests {% endblock %}

{% block content %}
    <h1>Tests</h1>
    <hr>
    {% for category in categories %}
        <a href="{% url 'app:question_list' category.slug %}">{{ category.name }}</a>
        <br>
    {% endfor %}
{% endblock %}